export const HOME = '/'
export const GAMIFICATION = '/gamification/'
export const LOGIN = '/login/'
export const REGISTER = '/register/'
export const REGISTER_STEP2 = '/register-step2/'
export const FORGOT_PASSWORD = '/forgot-password/'

export const THANK_YOU = '/thank-you/'

export const PRODUCT_COURSE = '/product/course/'
export const PRODUCT_SESSION = '/product/session/'

export const DOCUMENT_BLOG = 'https://aimacademy.vn/vi/blog'
export const DOCUMENT_PODCAST = '/document/podcast/'
export const DOCUMENT_PROJECT = '/document/project/'
export const DOCUMENT_TEST = '/document/test/'
export const DOCUMENT_YOUTUBE = '/document/video/'
export const DOCUMENT_EBOOK = '/document/ebook/'
export const DOCUMENT_GLOSSARY = '/document/glossary/'

export const CART = '/cart'
export const CART_MEMBERSHIP = '/cart/membership'
export const CART_CHECKOUT = '/cart/checkout/'
export const CART_MEMBERSHIP_CHECKOUT = '/cart/checkout-membership'
export const CART_ORDER_SUCCESS = '/cart/order-success/'

export const ACCOUNT_MY_PORTFOLIO = '/account/profile/'
export const ACCOUNT_VIEW_PROFILE = '/account/view-profile/'
export const ACCOUNT_ORDER_LIFETIME = '/account/order/lifetime/'
export const ACCOUNT_ORDER_MEMBERSHIP = '/account/order/membership/'
export const ACCOUNT_ELEARNING = '/account/elearning/'
export const ACCOUNT_ELEARNING_MEMBERSHIP = '/account/elearning/membership'
export const ACCOUNT_ADD_FRIEND = '/account/add-friend/'
export const ACCOUNT_WISHLIST = '/account/wishlist?slug=elearning'
export const ACCOUNT_NOTIFICATION = '/account/notification/'
export const ACCOUNT_MY_ACCOUNT = '/account/update-account/'
export const ACCOUNT_LEARN_OFFLINE = '/account/learn-offline/'
export const ACCOUNT_VIRTUAL_CLASS = '/account/virtual-class/'
export const ACCOUNT_AIM_COIN = '/account/aim-coin/'
export const ACCOUNT_VOUCHER = '/account/voucher/'
export const ACCOUNT_SUPPORT = '/account/support/'

export const BUSINESS_HOME = '/business/home/'
export const BUSINESS_OVERVIEW = '/business/overview/'
export const BUSINESS_PROFILE = '/business/profile/'
export const BUSINESS_UPDATE_ACCOUNT = '/business/update-account/'
export const BUSINESS_NOTIFICATION = '/business/notification/'
export const BUSINESS_FAQS = '/business/faqs/'
export const BUSINESS_STUDY_PLAN = '/business/study-plan/'
export const BUSINESS_STUDY_PLAN_DETAIL = '/business/study-plan/detail'
export const BUSINESS_STUDY_PLAN_ADD_SESSION = '/business/study-plan/add-session'
export const BUSINESS_STUDY_PLAN_ADD_MEMBER = '/business/study-plan/add-member'
export const BUSINESS_HISTORY_TRANSACTION = '/business/profile/history-transc/'
export const BUSINESS_ADMIN = '/business/profile/admin-management/'
export const BUSINESS_THANKS = '/business/thanks/'

export const LEARNING = '/learning'

export const LINK_PRIVACY_POLICY = 'https://aimacademy.vn/vi/chinh-sach-bao-mat'
